"""Package a Facet release for one platform, plus the script installer.

Facet 2.0 ships one native executable, `facet`. Its guidance (skills, packs,
agents and tool schemas) is compiled into it, so the platform archive holds:

  bin/facet[.exe]             built from ./cmd/facet with -X main.Version,
                              stripped (-s -w); on Windows with version
                              information and a manifest
  dependencies/remotion-composer/
                              the allowlisted composer sources named in
                              remotion-composer/composer-manifest.json, with
                              package.json, package-lock.json, tsconfig.json and
                              composer-manifest.json (dependencies are installed
                              by the installer, never shipped); the composer is
                              a media dependency of the Toolkit, beside the
                              others the installer adds under dependencies/
  LICENSE
  THIRD_PARTY_NOTICES.md      generated by scripts/generate-notices.py for the
                              same GOOS/GOARCH

The installer archive is platform independent: install.ps1, install.sh and
installer/{manifest.tsv,verify.html}, with the manifest's release row
stamped from package.json. Every archive is deterministic: sorted entries,
fixed timestamps and LF line endings for text.

Usage:
  python scripts/package-release.py --os windows --arch amd64 --out build/release
"""
import argparse
import hashlib
import json
import os
from pathlib import Path, PurePosixPath
import re
import subprocess
import sys
import tempfile
import zipfile

REPO = Path(__file__).resolve().parent.parent
COMPOSER = "remotion-composer"
# Where the composer sits inside a runtime, beside the other media
# dependencies; the Go toolbox finds it at <runtime>/dependencies/remotion-composer.
COMPOSER_RUNTIME_DIR = "dependencies/" + COMPOSER
COMPOSER_METADATA = ("package.json", "package-lock.json", "tsconfig.json", "composer-manifest.json")
INSTALLER_FILES = ("install.ps1", "install.sh", "installer/manifest.tsv", "installer/verify.html")
VERSION_PATTERN = re.compile(r"^\d+\.\d+\.\d+(?:-[A-Za-z0-9.-]+)?$")
TEXT_SUFFIXES = {"", ".json", ".ts", ".tsx", ".md", ".txt", ".html", ".tsv", ".ps1", ".sh"}
FIXED_TIME = (1980, 1, 1, 0, 0, 0)
BUILD_TIMEOUT = 900
# Compiles the Windows version information and manifest into a resource
# object at build time; pinned, and verified against the Go checksum database.
# Nothing from it is linked into facet.
GO_WINRES = "github.com/tc-hib/go-winres@v0.3.3"


class PackageError(Exception):
    """The release cannot be packaged faithfully."""


def read_version():
    version = json.loads((REPO / "package.json").read_text(encoding="utf-8"))["version"]
    if not VERSION_PATTERN.match(version):
        raise PackageError(f"package.json version {version!r} is not a release version")
    return version


def normalized(name, data):
    """Text files ship with LF line endings, whatever the checkout uses."""
    if PurePosixPath(name).suffix.lower() in TEXT_SUFFIXES:
        try:
            text = data.decode("utf-8")
        except UnicodeDecodeError:
            return data
        return text.replace("\r\n", "\n").encode("utf-8")
    return data


def add_entry(archive, name, data, executable=False):
    info = zipfile.ZipInfo(name, date_time=FIXED_TIME)
    info.create_system = 3  # Unix permissions, read by unzip and the installers
    info.external_attr = (0o100755 if executable else 0o100644) << 16
    info.compress_type = zipfile.ZIP_DEFLATED
    archive.writestr(info, data)


def composer_files():
    """The composer files to ship, relative to remotion-composer/."""
    manifest_path = REPO / COMPOSER / "composer-manifest.json"
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as error:
        raise PackageError(f"cannot read {manifest_path}: {error}") from error
    sources = manifest.get("allowedSourcePaths") if isinstance(manifest, dict) else None
    if not isinstance(sources, list) or not sources or not all(isinstance(item, str) for item in sources):
        raise PackageError(f"{manifest_path} must list allowedSourcePaths")
    names = list(COMPOSER_METADATA) + sources
    if len(set(names)) != len(names):
        raise PackageError(f"{manifest_path} names a file twice")
    for name in names:
        path = PurePosixPath(name)
        if (not path.parts or path.is_absolute() or "\\" in name or ".." in path.parts
                or any(part == "node_modules" or part.startswith(".") for part in path.parts)):
            raise PackageError(f"unsafe composer path in {manifest_path}: {name!r}")
        if name not in COMPOSER_METADATA and path.parts[0] != "src":
            raise PackageError(f"allowlisted composer source outside src/: {name}")
        source = REPO / COMPOSER / Path(*path.parts)
        if source.is_symlink() or not source.is_file():
            raise PackageError(f"composer file is missing or not a regular file: {COMPOSER}/{name}")
    return sorted(names)


def installer_content(name, version):
    data = (REPO / name).read_bytes()
    text = data.decode("utf-8").replace("\r\n", "\n")
    if name.endswith(".ps1") and not text.isascii():
        # Windows PowerShell 5.1 reads a script without a byte-order mark as
        # ANSI, so the PowerShell installer must stay ASCII.
        raise PackageError(f"{name} must contain only ASCII characters")
    if name == "installer/manifest.tsv":
        rows = [line.split("\t") for line in text.splitlines()]
        stamped = 0
        for row in rows:
            if row[:2] == ["release", "facet"] and len(row) > 2:
                row[2] = version
                stamped += 1
        if stamped != 1:
            raise PackageError("installer/manifest.tsv must contain exactly one release/facet row")
        text = "\n".join("\t".join(row) for row in rows) + "\n"
    return text.encode("utf-8")


def build_installer(out, version):
    path = out / f"facet-installer-{version}.zip"
    with zipfile.ZipFile(path, "w") as archive:
        for name in sorted(INSTALLER_FILES):
            add_entry(archive, name, installer_content(name, version), executable=name.endswith(".sh"))
    return path


def run(command, env=None):
    try:
        subprocess.run(command, cwd=REPO, env=env, check=True, timeout=BUILD_TIMEOUT)
    except FileNotFoundError as error:
        raise PackageError(f"{command[0]} is required but was not found") from error
    except subprocess.CalledProcessError as error:
        raise PackageError(f"{' '.join(command[:3])} ... exited {error.returncode}") from error
    except subprocess.TimeoutExpired as error:
        raise PackageError(f"{' '.join(command[:3])} ... timed out") from error


def build_platform(out, version, goos, goarch, work):
    suffix = ".exe" if goos == "windows" else ""
    binary = work / ("facet" + suffix)
    env = dict(os.environ, GOOS=goos, GOARCH=goarch, CGO_ENABLED="0")
    # Stripped of the symbol table and DWARF data, which a release does not
    # need (Go keeps what panics and stack traces use).
    build = ["go", "build", "-trimpath", "-ldflags", f"-s -w -X main.Version={version}", "-o", str(binary), "./cmd/facet"]
    if goos != "windows":
        run(build, env=env)
    else:
        # Windows builds say what they are: version information (product
        # Facet, the release version, its publisher) and an application
        # manifest, compiled from a resource object that `go build` links
        # because it sits in the package directory, and removed again.
        # Microsoft Defender flagged the published 2.1.0 and 2.1.1
        # windows/amd64 binaries, which carried neither, with a
        # machine-learning verdict (Trojan:Win32/Bearfoos.A!ml).
        resource = REPO / "cmd" / "facet" / f"rsrc_windows_{goarch}.syso"
        run(["go", "run", GO_WINRES, "simply", "--arch", goarch, "--out", str(REPO / "cmd" / "facet" / "rsrc"),
             "--manifest", "cli", "--product-name", "Facet", "--file-description", "Facet Toolkit",
             "--product-version", version, "--file-version", version, "--original-filename", "facet.exe",
             "--copyright", "Facet Contributors. AGPL-3.0-or-later."], env=dict(os.environ, CGO_ENABLED="0"))
        try:
            if not resource.is_file():
                raise PackageError(f"go-winres did not write {resource.name}")
            run(build, env=env)
        finally:
            resource.unlink(missing_ok=True)
    notices = work / "THIRD_PARTY_NOTICES.md"
    run([sys.executable, str(REPO / "scripts" / "generate-notices.py"), "--goos", goos, "--goarch", goarch, "--out", str(notices)])
    path = out / f"facet-{version}-{goos}-{goarch}.zip"
    entries = {
        "bin/facet" + suffix: (binary.read_bytes(), True),
        "LICENSE": (normalized("LICENSE", (REPO / "LICENSE").read_bytes()), False),
        "THIRD_PARTY_NOTICES.md": (normalized("THIRD_PARTY_NOTICES.md", notices.read_bytes()), False),
    }
    for name in composer_files():
        source = REPO / COMPOSER / Path(*PurePosixPath(name).parts)
        entries[f"{COMPOSER_RUNTIME_DIR}/{name}"] = (normalized(name, source.read_bytes()), False)
    with zipfile.ZipFile(path, "w") as archive:
        for name in sorted(entries):
            data, executable = entries[name]
            add_entry(archive, name, data, executable)
    return path


def sha256(path):
    digest = hashlib.sha256()
    with open(path, "rb") as stream:
        for block in iter(lambda: stream.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--os", required=True, choices=["windows", "linux", "darwin"])
    parser.add_argument("--arch", required=True, choices=["amd64", "arm64"])
    parser.add_argument("--out", required=True)
    parser.add_argument("--installer-only", action="store_true", help="assemble only the installer archive, for script-level tests")
    args = parser.parse_args(argv)
    try:
        version = read_version()
        out = Path(args.out).resolve()
        out.mkdir(parents=True, exist_ok=True)
        installer = build_installer(out, version)
        if args.installer_only:
            (out / "installer-checksums.txt").write_text(f"{sha256(installer)}  {installer.name}\n", encoding="utf-8", newline="\n")
            print(json.dumps({"installer": str(installer)}))
            return 0
        with tempfile.TemporaryDirectory(prefix="facet-package-") as work:
            archive = build_platform(out, version, args.os, args.arch, Path(work))
        checksums = out / f"checksums-{args.os}-{args.arch}.txt"
        checksums.write_text("".join(f"{sha256(path)}  {path.name}\n" for path in (archive, installer)), encoding="utf-8", newline="\n")
    except PackageError as error:
        print(f"package-release: error: {error}", file=sys.stderr)
        return 1
    print(json.dumps({"archive": str(archive), "installer": str(installer), "checksums": str(checksums)}))
    return 0


if __name__ == "__main__":
    sys.exit(main())
